# fly.toml app configuration file generated for cortex-bot on 2024-06-04T00:05:40-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cortex-bot'
primary_region = 'yyz'

[build]
